name: Trigger OpenConnector API

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  trigger_api:
    runs-on: ubuntu-latest
    steps:
      - name: Call OpenConnector API endpoint
        run: |
          curl -X POST -u "${{ secrets.INLOG }}:${{ secrets.WACHTWOORD }}" "https://${{ secrets.DOMEINNAAM }}/index.php/apps/openconnector/api/synchronizations-run/1?test=false&force=true"
